project:
  type: website

website:
  title: "Codebreaker Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard  
      - href: about.qmd
        text: About

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



